import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Autodrone - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.droneLightMain}>
        <header className="flex">
          <div className={styles.droneLightIcon}>
            <Image src="/drone-icon.png" width={75} height={35} />
          </div>
          <div className={styles.droneLightHeaderMenu}>
            <a href="">HOME</a>
          </div>
          <div className={styles.droneLightHeaderMenu}>
            <a href="">GALLERY</a>
          </div>
          <div className={styles.droneLightHeaderMenu}>
            <a href="">PRODUCTS</a>
          </div>
          <div className={styles.droneLightHeaderMenu}>
            <a href="">REVIEW</a>
          </div>
          <div className={styles.droneLightHeaderMenu}>
            <a href="">SUPPORT</a>
          </div>
          <div className={styles.droneLightHeaderMenu}>
            <a href=""><Image src="/search-icon.png" width={25} height={25} /></a>
          </div>
          <div className={styles.droneLightHamburger}>
            <a href=""><Image src="/hamburger.png" width={18} height={14.85} /></a>
          </div>
        </header>

        <div className={styles.droneLightDetails}>
          <h1 className={styles.droneLightContentTitle}>Representing Drone Light</h1>
          <p className={styles.droneLightContentDescription}>Look up the sky and beautiful world with simple navigation. Just record and get a lot memories to share, lightly and fast like a lightning</p>
          {/* <p className={styles.droneLightContentDescription}></p> */}
          <button className={styles.droneLightGetNowBtn}>
            <a href="">GET NOW</a>  
          </button>
        </div>

        <div className={styles.droneLightPic}>
          <Image src="/Hero Image 1.png" width={1440} height={750} />
        </div>
      </div>

      <div className={styles.droneLightFacility}>
        <div className={styles.droneLightLeftFacility}>
          <div className={styles.ultraLightFacility}>
            <span className={styles.ultraLightTitle}>Ultra Light</span>
            <p className={styles.ultraLightDescription}>Drone move faster with weighing</p>
            <p className={styles.ultraLightDescription}>component <span className="text-black">under 200 g</span></p>
          </div>
          <div className={styles.ultraLightPic}>
            <Image src="/ultra_light 1.png" width={940} height={660} />
          </div>
        </div>
        <div className={styles.droneLightRightFacility}>
          <div className={styles.bestResolutionFacility}>
            <span className={styles.bestResolutionTitle}>Best Resolution</span>
            <p className={styles.bestResolutionDescription}>Take a beautiful view with best camera</p>
            <p className={styles.bestResolutionDescription}>up to <span className="text-white">under 200 g</span></p>
          </div>
          <div className={styles.bestResolutionPic}>
            <Image src="/best_resolution 1.png" width={940} height={660} />
          </div>
        </div>  
      </div>

      <div className={styles.whyDroneLight}>
        <div className={styles.whyDroneLightContainer}>
          <div className={styles.whyDroneLightPic}>
              <Image src="/benefit_feature_image 1.png" width={342} height={358} />
          </div>
          <div className={styles.whyDroneLightInfoContainer}>
            <div className={styles.whyDroneLightTitle}>
              Why Drone Light?
            </div>
            <div className={styles.whyDroneLightDescription}>
              We provide a best self drone easy to use and operate. With auto pilot, the device will take a beautiful view for the best of flying operation.
            </div>
            <div className={styles.whyDroneLightSpecs}>
              <div className={styles.whyDroneLightSpecsGroup}>
                <div className={styles.whyDroneLightMainText}>
                  <div className={styles.whyDroneLightText}>4K</div>
                  <div className={styles.whyDroneLightSubText}>Camera Resolution</div>
                </div>
                <div>
                  <div className={styles.whyDroneLightText}>2TB</div>
                  <div className={styles.whyDroneLightSubText}>Storage Capacity</div>
                </div>
              </div>
              <div className={styles.whyDroneLightSpecsGroup}>
                <div className={styles.whyDroneLightMainText}>
                  <div className={styles.whyDroneLightText}>60m/s</div>
                  <div className={styles.whyDroneLightSubText}>Super Max Speed</div>
                </div>
                <div className="ml-4">
                  <div className={styles.whyDroneLightText}>30 mins</div>
                  <div className={styles.whyDroneLightSubText}>Long Flight Time</div>
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </div>

      <div className={styles.droneLightNewProducts}>
        <div>
          <div className={styles.newProductsTitle}>New Products</div>
          <p className={styles.newProductsDescription}>New innovation, best quality than before. Make every moment flying operation become unforgettable</p>
        </div>
        <div className={styles.newProductItemContainer}>
          <div className={styles.newProductsItem}>
            <div>
              <Image className="rounded-lg" src="/mini_drone 1.png" alt="Vercel Logo" width={410} height={240} />
            </div>
            <div>
              <div className={styles.newProductsItemName}>Mini Drone</div>
              <div className={styles.newProductsItemDescription}>Powerful camera drone at an affordable price range. Camera up to 4K resolution, optimize shots automatically.</div>
              <div>
                <button className={styles.droneLightGetNowBtn}>GET NOW</button>
              </div>
            </div>
          </div>
          <div className={styles.newProductsItem}>
            <div>
              <Image className="rounded-lg" src="/drone_light 1.png" alt="Vercel Logo" width={410} height={240} />
            </div>
            <div>
              <div className={styles.newProductsItemName}>Drone Light</div>
              <div className={styles.newProductsItemDescription2}>Drone light is every creators dream. Setting apperture manually and high battery performance. Drone light is everything you need.</div>
              <div>
                <button className={styles.droneLightGetNowBtn}>GET NOW</button>
              </div>
            </div>
          </div>
          <div className={styles.newProductsItem}>
            <div>
              <Image className="rounded-lg" src="/mini_drone 1.png" alt="Vercel Logo" width={410} height={240} />
            </div>
            <div>
              <div className={styles.newProductsItemName}>Mini Drone</div>
              <div className={styles.newProductsItemDescription}>Powerful camera drone at an affordable price range. Camera up to 4K resolution, optimize shots automatically.</div>
              <div>
                <button className={styles.droneLightGetNowBtn}>GET NOW</button>
              </div>
            </div>
          </div>
          <div className={styles.newProductsItem}>
            <div>
              <Image className="rounded-lg" src="/drone_light 1.png" alt="Vercel Logo" width={410} height={240} />
            </div>
            <div>
              <div className={styles.newProductsItemName}>Drone Light</div>
              <div className={styles.newProductsItemDescription2}>Drone light is every creators dream. Setting apperture manually and high battery performance. Drone light is everything you need.</div>
              <div>
                <button className={styles.droneLightGetNowBtn}>GET NOW</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className={styles.productReview}>
        <div className={styles.productReviewTitle}>What Our Pilots Are Saying</div>
        <div className={styles.productReviewCardContainer}>
          <div className={styles.productReviewCard}>
            <div className={styles.productReviewText}>With high resolution camera, picture become clear and beautiful. Its so easy to operate drone.</div>
            <div className={styles.productReviewerDetail}>
              <div>
                <Image className="rounded-full" src="/profile1 1.png" alt="Vercel Logo" width={70} height={70} />
              </div>
              <div className="ml-8">
                <div className={styles.productReviewerName}>Hugo Adams</div>
                <div className={styles.productReviewerJob}>Content Creator</div>
              </div>
            </div>
          </div>
          <div className={styles.productReviewCard}>
            <div className={styles.productReviewText}>Taking high view video become easy and faster. Battery performance really helping for making film</div>
            <div className={styles.productReviewerDetail}>
              <div>
                <Image className="rounded-full" src="/profile2 1.png" alt="Vercel Logo" width={70} height={70} />
              </div>
              <div className="ml-8">
                <div className={styles.productReviewerName}>Jennie Obrien</div>
                <div className={styles.productReviewerJob}>Director Film</div>
              </div>
            </div>
          </div>
          <div className={styles.productReviewCard}>
            <div className={styles.productReviewText}>Making video content for my trip vlog so powerful and wonderdul. Love the video quality.</div>
            <div className={styles.productReviewerDetail}>
              <div>
                <Image className="rounded-full" src="/profile3 1.png" alt="Vercel Logo" width={70} height={70} />
              </div>
              <div className="ml-8">
                <div className={styles.productReviewerName}>Lisa Millz</div>
                <div className={styles.productReviewerJob}>Content WQCreator</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <footer className={styles.autoDroneFooter}>
        <div className={styles.autoDroneFooterContainer}>
          <div className={styles.autoDroneFooterHead}>
            <div className={styles.droneLightIcon}>
              <Image src="/drone-icon.png" width={75} height={35} />
              <span className={styles.autoDroneFooterTitle}>autoDrone</span>
            </div>
            <div className={styles.autoDroneFooterText}>Look up the sky and beautiful world easily.</div>
          </div>
          <div className={styles.autoDroneFooterMenuContainer}>
            <div className={styles.autoDroneFooterMenu}>Explore</div>
            <div className={styles.autoDroneFooterSubMenu}>Our Service</div>
            <div className={styles.autoDroneFooterSubMenu}>Specification</div>
            <div className={styles.autoDroneFooterSubMenu}>Refund</div>
            <div className={styles.autoDroneFooterSubMenu}>Playlist</div>
          </div>
          <div className={styles.autoDroneFooterMenuContainer}>
            <div className={styles.autoDroneFooterMenu}>Account</div>
            <div className={styles.autoDroneFooterSubMenu}>My Account</div>
            <div className={styles.autoDroneFooterSubMenu}>Top Benefit</div>
            <div className={styles.autoDroneFooterSubMenu}>How-to Tutorials</div>
            <div className={styles.autoDroneFooterSubMenu}>Moment</div>
          </div>
          <div className={styles.autoDroneFooterMenuContainer}>
            <div className={styles.autoDroneFooterMenu}>Office</div>
            <div className={styles.autoDroneFooterSubMenu}>+021 2208 1996</div>
            <div className={styles.autoDroneFooterSubMenu}>SCBD, Jakarta</div>
            <div className={styles.autoDroneFooterSubMenu}>No.2 (Autodrone)</div>
            <div className={styles.autoDroneFooterSubMenu}>Support@autodrone.id</div>
          </div>
        </div>
      </footer>
    </div>
  )
}
